### ISSUE TITLE
Unable to encode function call

### ISSUE THREAD

**Issue by pbeneteau** [fubuloubu/eth-abi#159]
I'm trying to encode a function call to retrieve the token URI on an etc contract:

`encode_single('tokenURI(uint256)', token_id)`

I pass the function name and type and then the token id as int. I get this error:

>  Parse error at '(uint' (column 9) in type string 'tokenURI(uint256)'

Please help!

**Comment by fselmo** [comment]
Hey @stealdre. `tokenURI` is not a defined abi type. `eth-abi`'s `encode_single()` is strictly going to be a tool to encode abi types. i.e. if you wanted to encode a single `uint256`, the right approach might be `encode_single('uint256', token_id)`. If you wanted to get the function identifier you'd need the first 4 bytes of the keccak256 hash for `"tokenURI(uint256)"`, not an abi encoding.

All that aside, I'd recommend checking out [web3.py](https://github.com/ethereum/web3.py) and reading the [documentation](https://github.com/ethereum/web3.py) on instantiating a `web3.eth.contract()` object. You can then more easily make the desired call by invoking `contract.functions.tokenURI(token_id).call()`, for example, without needing to build the data payload yourself.

I'm going to close this as this doesn't seem to be an issue with the library but do consider joining the [ethereum python developers discord](https://discord.gg/GHryRvPB84) where usage questions are encouraged. Best of luck.

**Comment by pbeneteau** [comment]
Thing is I don't want to call the function, but only encode the call.
