### ISSUE TITLE
[Project Management] When will eth-abi>=4.0.0 be released?

### ISSUE THREAD

**Issue by martin-thoma** [fubuloubu/eth-abi#200]
I'm curious about the process and could not find any hints on what the blockers are / if there is a timeline.

On https://pypi.org/project/eth-abi/#history I see that `eth-abi==4.0.0b2` was released in November 2022. But what needs to happen that it becomes a "normal" release, not a pre-release?

[web3==6.0.0](https://pypi.org/project/web3/#history) was released yesterday, but it depends on `eth-abi>=4.0.0b2`

**Comment by kclowes** [comment]
Once #201 is merged, I'll release one more beta version to make sure everything looks good with web3 v6 and then I'll release eth-abi v4 stable. Assuming everything looks good, we'll plan to get it out next week sometime.

**Comment by martin-thoma** [comment]
Thank you :pray:
